name = "mc-4-modpack"
author = "SourcierDeVerite"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a49147e99f73e08335c328cb320348c602f64659e2e1bbc624f71196c2889cc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
