name = "mc-4-modpack"
author = "SourcierDeVerite"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14485e04e622293bd5c61a7f4cc4a933925b3b7167479cc916ffb4cb53f7328c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
