name = "mc-4-modpack"
author = "SourcierDeVerite"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e78952d565ca98c6940ccc4e9caff81829964fb9f79eb6039a70bd74176f95ca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
